services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - app_network
    volumes:
      - ./apps/web:/app  # Adjust this path based on your project structure

  api:
    container_name: api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    restart: always
    ports:
      - 3001:3001
    networks:
      - app_network
    volumes:
      - ./apps/api:/app  # Adjust this path based on your project structure

networks:
  app_network:
    external: true
